### ISSUE TITLE
Question about evaluation 

### ISSUE THREAD

**Issue by Elfsong** [allenai/scifact-leaderboard#2]
Hi @dwadden , I found there is at most one abstract for each claim in "predictions_small.jsonl". You call it Rationale in your paper. What if a rationale needs sentences from more than two abstracts? Like that:

`{"id": 452, "claim": "Gene expression does not vary appreciably across genetically identical cells.", "evidence": {"12804937": [{"sentences": [0], "label": "CONTRADICT"}], "464511": [{"sentences": [0], "label": "CONTRADICT"}]}, "cited_doc_ids": [12804937, 464511]}`

If my model finally uses {"12804937", [0]} and {"464511", [0]} as evidences, how to construct the prediction.jsonl?

**Comment by Elfsong** [comment]
```
The abstracts that either SUPPORT or REFUTE c are referred to as evidence abstracts for c, denoted as E(c). 
Each evidence abstract a ∈ E(c) is annotated with rationales. 
A single rationale Ri is a collection of sentences {r1(c, a), . . . , rm(c, a)}, 
where m is the number of sentences in rationale Ri. 
We denote the set of all rationales as R(c, a) = {R1(c, a), . . . , Rn(c, a)}.
```

As the paper mentioned, all sentences in one rationale should come from the same abstract? 

```
Note that though the gold annotations may contain multiple separate rationales, 
to simplify the prediction task we only require the model to predict a single collection of rationale sentences; 
these sentences may encompass multiple gold rationales.
```

Which means we only need sentences from one abstract for the evaluation? Sorry I was really confused with this section.

**Comment by Elfsong** [comment]
I figured it out! lols

**Comment by dwadden** [comment]
Haha OK, glad you figured it out!
